version: '2'

services:
  zk:
    image: wurstmeister/zookeeper
    container_name: c1_zk
    restart: unless-stopped
    ports:
      - "2281:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: c1_kafka1
    ports:
      - "9192:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9192
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster1:/kafka

  kafka2:
    image: wurstmeister/kafka
    container_name: c1_kafka2
    ports:
      - "9193:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9193
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster1:/kafka

  kafka3:
    image: wurstmeister/kafka
    container_name: c1_kafka3
    ports:
      - "9194:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9194
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster1:/kafka
