version: '2'

services:
  zk:
    image: wurstmeister/zookeeper
    container_name: c0_zk
    restart: unless-stopped
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: c0_kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster0:/kafka

  kafka2:
    image: wurstmeister/kafka
    container_name: c0_kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster0:/kafka

  kafka3:
    image: wurstmeister/kafka
    container_name: c0_kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.68.29
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ~/codes/docker/data/kafka/cluster0:/kafka
